---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main
  event:
    - push
    - custom

steps:
  - name: install
    image: node:22
    commands:
      - npm ci

  - name: build
    image: node:22
    commands:
      - npm run build

  - name: deploy
    image: alpine
    volumes:
      - name: output
        path: /var/shared
    commands:
      - ls /var/shared
      - rm -rf /var/shared/*
      - cp -r build/* /var/shared

volumes:
  - name: output
    host:
      path: /root/services/shared/cubify-cuber
---
kind: signature
hmac: fcc4f607d633cd72523d179e088872082940f0e11ac7d429b4d6df24c839c1e0

...
