---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main
  event:
    - push
    - custom

steps:
  - name: install
    image: node:22
    commands:
      - npm ci

  - name: build
    image: node:22
    commands:
      - npm run build

  - name: deploy
    image: alpine
    volumes:
      - name: output
        path: /var/shared
    commands:
      - rm -rf /var/shared/*
      - cp -r dist/* /var/shared

volumes:
  - name: output
    host:
      path: /root/services/shared/cubify-cuber
---
kind: signature
hmac: c6d44de6a782af19e758d121abd3a0144132667a95819f05470066fa523890f8

...
