---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main
  event:
    - push
    - custom

steps:
  - name: install
    image: node:18
    commands:
      - npm ci

  - name: build
    image: node:18
    commands:
      - npm run build

  - name: deploy
    image: alpine
    volumes:
      - name: output
        path: /var/shared
    commands:
      - ls /var/shared
      - rm -rf /var/shared/*
      - cp -r build/* /var/shared

volumes:
  - name: output
    host:
      path: /root/services/shared/cubify-cuber
---
kind: signature
hmac: 55d66ed804b2482003630ac119c7212150b5f1f07895d36cc56b0a916ebbee68

...
